### ISSUE TITLE
How to use multi-cursor mode

### ISSUE THREAD

**Issue by allenhwkim** [aioutecism/amVim-for-VSCode#10]
Thanks for this extension.

README said

Visual Block mode: Please use multi-cursor instead.

My question is 

how to use multi-cursor mode to modify a block to insert or indent?

Thanks

**Comment by aioutecism** [comment]
Hi,

To insert:
Use `Cmd+Option+Up/Down` to add cursor. Then press `i` to enter Insert mode.

To indent:
I would simply select lines I want to indent in VisualLine mode and press `>>`.
