### ISSUE TITLE
^ (go to start) and $ (go to end)

### ISSUE THREAD

**Issue by Moncef12** [aioutecism/amVim-for-VSCode#100]
Hi,

Is it possible to have this (^ and $) ?

**Comment by aioutecism** [comment]
Hi @Moncef12 

`^` and `$` are already implemented.

**Comment by Moncef12** [comment]
Indeed, I was on an old version.

Thank you for this great extension ! I switched from WS to vscode for this (and vscode-icons) ,  keep up  !
