### ISSUE TITLE
Input Chinese word doesn't work correctly

### ISSUE THREAD

**Issue by sparetire** [aioutecism/amVim-for-VSCode#101]
Forgive my poor English.

After update version 1.6.2, when I input Chinese word with Google Pinyin IME or Microsoft Pinyin, in Chinese mode, eg. 

> peiz

And then select the first one, I want to get

> 配置

But I got a text like this

> 配配置配置

The words was repeated. There is no this issue in the last version.

Platform: Windows 10

VS Code: 1.2.0

amVim: 1.6.2

Thanks!

**Comment by fenbox** [comment]
the same problem looks like below:

![2016-06-07 23_09_31](https://cloud.githubusercontent.com/assets/360618/15863285/f833d274-2d04-11e6-93bd-fb4a9d373981.gif)

**Comment by localvar** [comment]
I met same issue on windows 10 profession, vscode 1.2.0, amVim 1.7.0.

when I want to input `价格` via `jiage`, I got:
` jiajiajia'gjia'gjia'gjia'gjia'gjia'gjia'gejia'gejia'gejia'gejia'gejia'gejia'gejia'gejia'ge价格价格价格价格价格价格价格`

**Comment by zhaohaidao** [comment]
I met the same issue

**Comment by takuan-osho** [comment]
I met the same issue in case of inputting Japanese language.

Platform: OS X El Capitan
VSCode: 1.2.0
amVim: 1.8.0

**Comment by aioutecism** [comment]
This is related to VSCode's input handling.
I'm finding a way to workaround it.

**Comment by freshcn** [comment]
＋1　i met the same issue

**Comment by shudingbo** [comment]
+1

**Comment by bravomikekilo** [comment]
+1
Ubuntu 16.04

**Comment by YiuTerran** [comment]
+1

I have to remove this extension now...

**Comment by Arata3** [comment]
+1 ;
now, I use vscode without vim bind, and made me edit file very slowly !

Platform: OS X El Capitan
VSCode: 1.2.1
amVim: 1.8.1

**Comment by localvar** [comment]
this should be a bug of VS Code, please comment on this issue to push the bug be fixed:
https://github.com/Microsoft/vscode/issues/8133
