### ISSUE TITLE
Occasionally freeze whole vim commands after update to 1.8.0

### ISSUE THREAD

**Issue by JamesKim2998** [aioutecism/amVim-for-VSCode#104]
Hi, thanks for brilliant work.
After update I'm experienced occasionally huge performance drop (like each 5min) just after any keystroke.
The major symptom is whole vim commands are just freezed, and then after few seconds(more than 5) whole commands I entered are played, but VSCode works fine while this thing happens.
It's easy to reproduce, but I cannot figure it out what condition made it happened.
At first I presumed its might be VSCode's bug, but after uninstall amVim, all problem got disappeared.

I'm now working on game project, which uses Unity Engine (C#).
The project is private one so I cannot show codes or any stuff...
CLOC: 194082

**Comment by JamesKim2998** [comment]
I confirmed this issue was just related with VSCode, not amVim.
Sorry for misunderstanding.

**Comment by aioutecism** [comment]
Yes.
It seems that background process management has changed since VSCode 1.2.0.
