### ISSUE TITLE
< and > should exit visual mode

### ISSUE THREAD

**Issue by tangentsoft** [aioutecism/amVim-for-VSCode#108]
Visual mode is very useful for indenting and unindenting blocks of code using the `<` and `>` commands. This works in amVim for a single level, but because it leaves you in Visual mode instead of switching to Normal mode, you can't then say `.` to shift another level the same direction or `u` to undo the indent level shift.

**Comment by aioutecism** [comment]
Fixed in 1.18.0.
Pull request here: #157.
