### ISSUE TITLE
amVim 3.0.0 can not input Chinese

### ISSUE THREAD

**Issue by scloudyy** [aioutecism/amVim-for-VSCode#109]
- VSCode Version: 1.2.1
- OS Version: win7
- amVim Version: 3.0.0: 

Steps to Reproduce:

When using Chinese input method to type one word, just like '沈' which is composed by 'shen', but there will appear a lot of unexpected words.
This bug appears only after amVim 3.0.0

![qq 20160622194309](https://cloud.githubusercontent.com/assets/15358886/16265443/fa9ef274-38b1-11e6-8d15-a7db86b8721a.png)

![qq 20160622194321](https://cloud.githubusercontent.com/assets/15358886/16265465/11d9e5d4-38b2-11e6-9fba-cdae045cb44c.png)

can also see https://github.com/Microsoft/vscode/issues/7997

**Comment by liukun** [comment]
Met the same issue. Use other extension for now https://marketplace.visualstudio.com/items?itemName=74th.vimStyle

**Comment by localvar** [comment]
this is not bug of the extensions, but VS Code.
please comment on this issue to push this be fixed: https://github.com/Microsoft/vscode/issues/8133

**Comment by aioutecism** [comment]
This has been fixed in amVim 1.8.2.
