### ISSUE TITLE
Horizontally navigating with VIM shortcuts (h, l, 0, $, t, f, etc) does not horizontal scroll

### ISSUE THREAD

**Issue by techniq** [aioutecism/amVim-for-VSCode#11]
Pressing non-VIM horizontal movement keys (left/right arrow, home, end, etc) will horizontal scroll the editor pane if needed to keep the cursor in the viewport, but pressing the vim shortcuts (h, l, 0, $, t, f, etc) does not.  Pressing an arrow key after the cursor has gone out of the viewport will scroll and show the cursor in the viewport.

Vertical scrolling does work though (j, k, G, gg, etc)

**Comment by aioutecism** [comment]
Thanks for the report.

This is a bug of VSCode's API (https://github.com/Microsoft/vscode/issues/1868).
I'm finding a work-around until they fix the bug.

**Comment by aioutecism** [comment]
Work around: cdf8a86850a6bfe3da4a8627de64c2218a30bb58

Please update to the newest version.

**Comment by techniq** [comment]
Workaround is working great.  Thanks
