### ISSUE TITLE
Navigate through blank lines using { and }

### ISSUE THREAD

**Issue by endel** [aioutecism/amVim-for-VSCode#110]
This is one of my most used navigation patterns. `{` should go to the previous blank line and `}` to the next one.

**Comment by tobia** [comment]
I think this issue will be marked as duplicate of #1 

Still, I use `{` and `}` all the time too, so I really hope someone with the knowledge will implement it soon!

**Comment by d-sparks** [comment]
+1

**Comment by aioutecism** [comment]
Supported in 1.23.0.
