### ISSUE TITLE
Cannot dismiss intellisense function parameter tooltip

### ISSUE THREAD

**Issue by mattijauhiainen** [aioutecism/amVim-for-VSCode#112]
Pressing esc doesn't dismiss the intellisense tooltip when filling in function parameters with amVim (which makes sense I guess, but...). To get rid of the tooltip, I need to navigate out of the function call, and once I get back to filling in the parameters the tooltip often reappears. This is annoying as the tooltip often covers code I want to see, so it would be great to have some convenient way to dismiss the tooltip. I'm on osX with vscode 1.3.1.

**Comment by aioutecism** [comment]
This should be fixed in amVim 1.8.4.
