### ISSUE TITLE
change word and '.' replay blocks further input

### ISSUE THREAD

**Issue by iivvoo** [aioutecism/amVim-for-VSCode#113]
One of my often used vim patterns is to change a word (cw) and replay the change later. However, this makes vscode (sometimes?) not accept any more input. Input, insert, deletion, nothing works anymore.
Not even in other tabs or after closing a tab.

You can somewhat break out of it by changing text (mouse selection followed by 'c') but in the end the only proper solution is to restart vscode entirely.

**Comment by aioutecism** [comment]
Thanks for the report.
This should be fixed in 1.10.2.
