### ISSUE TITLE
: command support

### ISSUE THREAD

**Issue by dasizeman** [aioutecism/amVim-for-VSCode#114]
In the project description page you mention that : commands are not supported.  Is there a reason for this?  I know that the vscodevim extension has implemented this, so it's definitely possible.  I am not too familiar with VSCode extension development yet but when I get some more free time I would be happy to work on this feature.  I am personally invested because I keep wanting to save with :w when using this extension.

**Comment by aioutecism** [comment]
`:` will not be supported because that's a step backward comparing to "Command Palette"(`Cmd+Shift+P` or `F1`). Besides, you can custom keybindings for faster access to commands.
