### ISSUE TITLE
Cursor's column position reduced to shortest line in vertical moves.

### ISSUE THREAD

**Issue by Liquidmantis** [aioutecism/amVim-for-VSCode#12]
Hopefully that makes sense.  For example if the cursor is at column 20 and moved through a line with only 10 characters the cursor is then at col 10.  Moving through an empty line resets the cursor to col 1.

**Comment by aioutecism** [comment]
This is a bug and will be fixed very soon.
https://github.com/aioutecism/amVim-for-VSCode/blob/cdf8a86850a6bfe3da4a8627de64c2218a30bb58/src/Actions/MoveCursor.ts#L24

**Comment by aioutecism** [comment]
Fixed in b6db0e0ecf1f2d879e690f7e170cee657a48d08f.
Please update to the latest version.

**Comment by Liquidmantis** [comment]
Great!  It's exciting seeing how quickly this extension is developing.  Thanks for it.
