### ISSUE TITLE
Unresponsive inside .gitignore file

### ISSUE THREAD

**Issue by andradei** [aioutecism/amVim-for-VSCode#124]
When I open `.gitignore` all the commands become unresponsive. Intellisense and arrow keys also stop.

All other files start behaving the same way _after_ opening a `.gitignore`

**Comment by aioutecism** [comment]
Do you have any extension related to `.gitignore` installed?
I'm thinking of conflict with other extensions.

**Comment by andradei** [comment]
The only thing I think would affect it is [Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory), but:

1. It is unlikely because it deals with `git log` and not `.gitignore`
2. After disabling `amVim` the issue was gone

**Comment by andradei** [comment]
More testing reveals it might not be a direct amVim issue:

I delete amVim and installed other vim extensions. They all behave the same.

The problem might be related to https://github.com/Microsoft/vscode/issues/10735, which I'm also getting on my Macbook

**Comment by aioutecism** [comment]
Heavy extension may delay VSCode's behavior.
Do you have logs in your `Output` panel when the problem occurs?

**Comment by andradei** [comment]
Not logs there unfortunately.

**Comment by aioutecism** [comment]
Cloud you give me the list of extensions in your VSCode? I may reproduce the problem.

**Comment by aioutecism** [comment]
And, how many files are there in your project?

**Comment by andradei** [comment]
- markdownlint
- Git History (git log)
- Go
- TODO Parser
- vscode-icons
- Rusty Code
- amVim

**Comment by aioutecism** [comment]
I was able to reproduce the problem.
Cloud you uninstall "TODO Parser" and try if the problem insist?

**Comment by andradei** [comment]
Uninstalled TODO Parser, everything works as normal.

I'm going to create and Issue there and reference this one.

Thank you.

**Comment by aioutecism** [comment]
You're welcome!
