### ISSUE TITLE
Can't delete multiple lines using <n>dd

### ISSUE THREAD

**Issue by thatchej** [aioutecism/amVim-for-VSCode#128]
**Example scenario**:

I want to delete 3 lines below the cursor, so I press 3dd.

**Expected**: The current line and 2 additional lines below the cursor are deleted

**Actual**: Nothing is deleted and the status bar shows `3 and ...`, resets after the first d, and then shows  `d and...`

**Comment by thatchej** [comment]
Other than this, I have been thoroughly loving this plugin. The more popular VSCode Vim plugin I was trying was pretty much unusable :)

**Comment by aioutecism** [comment]
`N dd` is not supported now.
Please be patient with the update.

As for now, you can use `d3j` to achive the same result.

**Comment by jonnypolite** [comment]
I didn't know `<n>dd` was a thing but I use `d<n>d` constantly and would love to see this work.

**Comment by aioutecism** [comment]
Supported in 1.22.0.
