### ISSUE TITLE
Undo/Redo should *never* leave text selected.

### ISSUE THREAD

**Issue by jordwalke** [aioutecism/amVim-for-VSCode#129]
As titled. Currently, undo leaves text selected. This is a very very common error in Vim plugins and I don't know why. It's devastating to your redo stack which is destroyed if you accidentally hit something like `u` with text selected (which changes the text casing and destroys the redo stack). Right now since `u` for change casing while selected is not implemented it doesn't destroy the redo stack, but `u` fails to continue undoing.

**Comment by aioutecism** [comment]
Thank you for your report!
This will be fixed very soon.

**Comment by aioutecism** [comment]
Fixed in 1.11.2.
