### ISSUE TITLE
Don't remove multiple cursors when changing to normal mode from insert mode

### ISSUE THREAD

**Issue by gerardabello** [aioutecism/amVim-for-VSCode#132]
When using multiple cursors, you can go from normal to insert mode keeping the cursors, but not back.

I see that the escape key triggers the function 'shrinkAStep' before going into normal mode. As far as I understand, this functions only purpose is to remove multiple cursors. I am wondering why it works like this, as I think keeping them is really useful.

**Comment by aioutecism** [comment]
Solved in 1.11.7. Enjoy!
