### ISSUE TITLE
`p` support in Visual Mode

### ISSUE THREAD

**Issue by zhangbowei** [aioutecism/amVim-for-VSCode#139]
e.g

console.log("Hello world");
console.log("Hello kitty");

Firstly, I copy some code by "y"(console.log("Hello kitty"); Then when I choose some code(console.log("Hello world"), I want to cover it(console.log("Hello world")) with the code(console.log("Hello kitty")) by "p".

I can't do this successfully.

**Comment by aioutecism** [comment]
This is not a bug. We haven't implied this feature now.

**Comment by aioutecism** [comment]
Added in 1.15.0.
