### ISSUE TITLE
Jump to line (#gg or #G)

### ISSUE THREAD

**Issue by techniq** [aioutecism/amVim-for-VSCode#14]
While `G` (top of file) and `gg` (bottom of file) are supporting, support is needed to allow prefixing either motion with a number to jump to a specific line

**Comment by aioutecism** [comment]
Yes, the current behavior is somehow wrong.

**Comment by aioutecism** [comment]
Support added in 262364e0c5af0b060b15ea2eb2a7f7daa53a1ddb.
Please update to the latest version.
