### ISSUE TITLE
Combination of numbers and commands (e.g., d+2+w)

### ISSUE THREAD

**Issue by jbkoh** [aioutecism/amVim-for-VSCode#145]
Hi, 

I would like to use the combination of numbers and commands. For example as in the title, d+2+w should delete 2 words. y+2+w would work same as well.

Thanks for developing this. I am using amVim extensively :)

**Comment by aioutecism** [comment]
N support for word motions added in 1.17.0 #146 .

**Comment by Episodex** [comment]
Can we also expect N support for line motions? Like d+3+d for deleting 3 lines, or > + 3 + > for indenting 3 lines? I found amVim most stable and convenient Vim extension and thank you for it :). I use line motions extensively so they would be most welcome.

**Comment by aioutecism** [comment]
@Episodex 
Of course. Please be patient for the updates.
