### ISSUE TITLE
escape should dismiss tooltip and go to normal mode?

### ISSUE THREAD

**Issue by kentor** [aioutecism/amVim-for-VSCode#147]
Current I have to press escape twice if there's a tooltip to go from insert to normal mode. This is a bit annoying.

**Comment by aioutecism** [comment]
Yes! That will be easier to use.

**Comment by aioutecism** [comment]
Fixed in 1.17.6.
Pull request here #156 .

**Comment by aioutecism** [comment]
Fixed in 1.17.6.
Pull request here #156 .
