### ISSUE TITLE
Visual mode paste (`p`) appends extra newline

### ISSUE THREAD

**Issue by jgoz** [aioutecism/amVim-for-VSCode#150]
Steps to reproduce:
- `Vy` - copy whole line in visual mode
- `Vp` - select whole line and paste over top

Expected behaviour:
- Line is pasted as-is

Actual behaviour:
- Line is pasted with extra trailing newline

**Comment by aioutecism** [comment]
Fixed in 1.17.4. See #152 for detail.

**Comment by jgoz** [comment]
Thanks for the fixes!
