### ISSUE TITLE
Multi-line text objects paste asymmetrically

### ISSUE THREAD

**Issue by jgoz** [aioutecism/amVim-for-VSCode#151]
When yanking or deleting inside a multi-line text object (e.g., `yi{` or `di(`), the contents are yanked/deleted correctly. But when pasting those contents inside of another pair of braces/brackets, the contents are _not_ inserted as expected. Instead, they are pasted on the next line with an extra leading newline and weird indentation on following line.

Example (cursor at `[]`):
```
{
    someFunction({
        a: 1,
        []b: 2
    });
    anotherFunction(1);
}
```

**`di{`**

```
{
    someFunction({[]});
    anotherFunction(1);
}
```

**`[p`**

*Expected:*
```
{
    someFunction({[]
        a: 1,
        b: 2
    });
    anotherFunction(1);
}
```

*Actual:*

```
{
    someFunction({});

        a: 1,
        []b: 2
        anotherFunction(1)
}
```

**Comment by aioutecism** [comment]
Fixed in 1.17.4. See #152 for detail.
