### ISSUE TITLE
Exiting insert mode, cursor is on wrong character

### ISSUE THREAD

**Issue by tomasiser** [aioutecism/amVim-for-VSCode#154]
In original vim, exiting the insert mode moves the cursor (_block_) on the character that was **in front of** the insert cursor (_pipe_). When you do the `i+ESC+i+ESC+...` sequence, the cursor keeps going backwards. Doing the `a+ESC+a+ESC+...` sequence keeps the cursor on the same place.

In the amVim extension, however, it's the opposite. The `i+ESC+i+ESC+...` keeps the cursor and `a+ESC+a+ESC+...` moves forward. This is because exiting the insert mode selects the character after the insert cursor. I believe this is a bug as it's not how vim behaves. :)

**Comment by aioutecism** [comment]
You are right!
Can't believe I didn't notice this one.

**Comment by aioutecism** [comment]
Fixed in 1.17.6.
Pull request here #155.
