### ISSUE TITLE
Ctrl+C does not go back to Normal mode!

### ISSUE THREAD

**Issue by lf94** [aioutecism/amVim-for-VSCode#16]
Please, please, please add this feature. I've tried the other 2 VSC vim extensions and they both do *not* support it either. Reaching for ESC is a pain on my hands. Having mapped Ctrl to Caps Lock (and leaving it that way for over a year), it's so much easier to do Ctrl+C.

**Comment by aioutecism** [comment]
I'll add this one today. 

Which system do you use?

**Comment by lf94** [comment]
Debian Jessie. Thank you!

**Comment by aioutecism** [comment]
Added in https://github.com/aioutecism/amVim-for-VSCode/releases/tag/0.0.12.

Please update to the newest version. Then change your configuration according to [README](https://github.com/aioutecism/amVim-for-VSCode#readme).
