### ISSUE TITLE
When startInInsertMode, change active editor from normal mode cursor would stay block

### ISSUE THREAD

**Issue by xg-wang** [aioutecism/amVim-for-VSCode#161]
It is not always so. I have debugged the extension for a while and it happens occasionally. Even the line `opt.cursorStyle = TextEditorCursorStyle.Line;` is executed the cursor still remains block.
It really makes me confused.

**Comment by xconverge** [comment]
FYI, I filed an issue with vscode that may be related, might help you out!

https://github.com/Microsoft/vscode/issues/17472

**Comment by xg-wang** [comment]
@xconverge Thx, I think that is a VSCode bug. Will watch that issue.

**Comment by aioutecism** [comment]
Thanks for your report.
I'll take a look into this as soon as possible.

**Comment by aioutecism** [comment]
I reproduced the bug and opened an issue here: https://github.com/Microsoft/vscode/issues/17513
