### ISSUE TITLE
Illegal file names on Windows

### ISSUE THREAD

**Issue by villasv** [aioutecism/amVim-for-VSCode#163]
Because `<` and `>` are illegal characters for file names in Windows, cloning the project breaks the repository integrity.

Not impossible to deal with, but makes life a little harder. Happens because of the files:
```
test/ModeVisual/<.test.ts
test/ModeVisual/>.test.ts
```

**Comment by aioutecism** [comment]
Oh. I'll fix it as soon as possible.

**Comment by aioutecism** [comment]
Fixed in 65b114b5140c49d88398fe5f4078e3edddd8882c.
