### ISSUE TITLE
p doesn't paste from system clipboard

### ISSUE THREAD

**Issue by pfmoore** [aioutecism/amVim-for-VSCode#166]
The ```p``` command doesn't paste from the system clipboard, and there's no equivalent of Vim's ```set clipboard=unnamed```.

How do I paste text I have copied from another application? And can this be made the behaviour of the ```p``` command, either via an option or by default, as it's crucial to me for the "feel" of Vim integrated with Windows.

**Comment by aioutecism** [comment]
@pfmoore 
System clipboard is not supported now. You can use the original shortcut (Ctrl+C/V), or if you have the `amVim.bindCtrlCommands` turned on, you could assign custom keybindings like this:
```
{ "key": "ctrl+shift+c", "command": "editor.action.clipboardCopyAction", "when": "editorTextFocus" },
{ "key": "ctrl+shift+v", "command": "editor.action.clipboardPasteAction", "when": "editorTextFocus && !editorReadonly" },
```

**Comment by pfmoore** [comment]
OK, thanks. Is there any timescale for system clipboard support?

**Comment by aioutecism** [comment]
@pfmoore 
Sorry, this is a subproject so I can't promise anything.
However, system clipboard support has high priority and will be added in next few versions.

**Comment by pfmoore** [comment]
No problem - I appreciate all the work you've put into the project, I'm not trying to push at all :-)

**Comment by zhangbowei** [comment]
I'm here waiting for this...

**Comment by theSoenke** [comment]
Is there any update on this? System clipboard support would be really great

**Comment by aioutecism** [comment]
@theSoenke 
I'll find time to work on this. Please wait for a little more.

**Comment by theSoenke** [comment]
@aioutecism Thank you!

**Comment by jleclanche** [comment]
@aioutecism Any updates on this? If you don't have time to work on it, I can give it a shot if you give me some pointers where to start :)

**Comment by karlhorky** [comment]
Bump @aioutecism just ran into this today, would be cool to have @jleclanche help out on implementation!

**Comment by aioutecism** [comment]
@karlhorky Thanks for the bump! I’m not sure if jleclanche can still help since the comment is 8 months ago. I’m happy to provide instructions if anyone can help the implementation.

**Comment by karlhorky** [comment]
So I've found some keybindings that seem to work here! 🥳

```json
  // Yank (copy) to system clipboard in VISUAL and VISUAL_LINE modes
  {
    "key": "y",
    "command": "editor.action.clipboardCopyAction",
    "when": "editorTextFocus && amVim.mode == 'VISUAL' && !inDebugRepl &&!suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "y",
    "command": "editor.action.clipboardCopyAction",
    "when": "editorTextFocus && amVim.mode == 'VISUAL LINE' && !inDebugRepl &&!suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  // Delete (cut) to system clipboard in VISUAL modes
  {
    "key": "d",
    "command": "editor.action.clipboardCopyAction",
    "when": "editorTextFocus && amVim.mode == 'VISUAL' && !inDebugRepl &&!suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
```

### Caveats

- The active selection from the `VISUAL` modes stays with the yank keybindings

I'm also uncertain why I don't need to match for `VISUAL LINE` mode with the `d` keybinding - it just works in both modes. Maybe more mode bugginess?

---

There is one more binding that I originally wrote to paste from system clipboard in `NORMAL` mode, but it **pastes even in `INSERT` mode** 😳 (I guess there's some issue with the modes):

```json
  // Paste from system clipboard only in NORMAL mode (not working - pastes also in INSERT mode)
  {
    "key": "p",
    "command": "editor.action.clipboardPasteAction",
    "when": "editorTextFocus && amVim.mode == 'NORMAL' && !inDebugRepl &&!suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
```

@aioutecism can you comment on why the mode check is not working here? I tried looking through the code, but I'm really lost there...

**Comment by karlhorky** [comment]
In https://github.com/aioutecism/amVim-for-VSCode/issues/17#issuecomment-522251645 I've found some potential keybindings for yank and delete actions, but the paste keybinding I tried isn't quite working yet!

**Comment by karlhorky** [comment]
@aioutecism can you post the instructions for pasting **and** copying (#17) from the system clipboard here? I may have some time to take a look at this soon.

**Comment by karlhorky** [comment]
The version that you wrote about in your 2016 comment in https://github.com/aioutecism/amVim-for-VSCode/issues/17#issuecomment-170748211 would also probably be acceptable to most people who want this feature:

> I can let `y` to make a selection then copy to clipboard, but this will make selections "blink".

Could be a default-off setting, if you think it would be too distracting for those not interested in this feature.

**Comment by aioutecism** [comment]
@karlhorky VSCode now has an [API](https://code.visualstudio.com/api/references/vscode-api#Clipboard) to access system clipboard so this should be pretty easy to implement.

The [`ActionRegister`](https://github.com/aioutecism/amVim-for-VSCode/blob/master/src/Actions/Register.ts) class is handling copy/paste actions. So we need to replace some logic to use system clipboard.

And I think we should add a default-off setting for it, and/or provide extra key bindings.

**Comment by karlhorky** [comment]
Oh great! I'll see if I can find some time in the next days to take a shot at implementing!

**Comment by karlhorky** [comment]
My first shot at a pull request up at #260.

**Comment by karlhorky** [comment]
Done in `master` (#260 was merged)! Will be released soon.

#271 contains documentation of the option.
