### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by vavans** [aioutecism/amVim-for-VSCode#167]
Even if its main competitor (Vim) is far more advanced, amVim is more reliable (Vim extension doesn't support snippets, it moves cursor erratically sometimes, etc.).
Since the last commit is from dec. 2016, i would like to know if the author will maintain amVim anymore ?
I'm not asking that to put any pressure, just to know if opening issues and working on PR is worth :) 
Or if we should go back working on Vim extension.

**Comment by aioutecism** [comment]
@vavans 
This repo is still maintained. I have little time to add features recently, but I'm using it every day, and it is stable.
You are very welcome to contribute to this project. I'll fix any bugs and review PRs as soon as possible.
Thanks.

**Comment by vavans** [comment]
I totally understand that you don't have enough time to work on an open source project all day long :) So it's a great news.
