### ISSUE TITLE
high cpu when typing

### ISSUE THREAD

**Issue by transtone** [aioutecism/amVim-for-VSCode#168]
when insert text to this code, It's quickly very slow and cpu goes 100%.
```vue
<tab-item :selected="demo3 === item" vk v-for="(item, index) in list3" :class="{'vux-1px-r': index !== list3.length-1}" @click="demo3 = item"
          :key="index">{{item}}</tab-item>
```

**Comment by aioutecism** [comment]
@transtone 
Please provide more info on how to reproduce the problem.
- Extensions you installed.
- Language mode you are using when the problem occurs.

**Comment by transtone** [comment]
I try to uninstall the other extensions. 
when I disable the amvim, It's ok. but I teast the `vimStyle` amd `vim for vscode` get the same bug.

**Comment by aioutecism** [comment]
@transtone 
OK.
I'm closing this issue.
