### ISSUE TITLE
amVim tutorial and tips for starters

### ISSUE THREAD

**Issue by calebeaires** [aioutecism/amVim-for-VSCode#175]
Hello community. Thanks for this extension.  I have study VIM, so I came here to ask the community for some video or tutorial with tips on how to use amVim on VSCode. Something like must used commands, ways to do this or that! Some tutorial like this will help **dev starters** (like me and many others) to understand how make things happen!

Any way..... thanks for your support!

**Comment by aioutecism** [comment]
amVim aims to enable Vim-like operations in VSCode, not to build a new way of editing.
I recommend you reading tutorials for Vim and try them inside VSCode(with amVim).
Here is a good start for you:
https://neovim.io/doc/user/index.html#doc-file-list

**Comment by dongzhonghua** [comment]
how to replace escape with j+j in insert mode?

**Comment by aioutecism** [comment]
@dongzhonghua 
Custom mapping is not implemented now. Please subscribe to #115 if you're interested in the updates.
