### ISSUE TITLE
Switching tabs sometimes doesn't preserve the line the cursor was at

### ISSUE THREAD

**Issue by nerdo** [aioutecism/amVim-for-VSCode#176]
I'm not sure the exact circumstances when this happens, but if I have several files A.txt and B.txt open and I'm currently in the middle of editing A.txt and switch to B.txt, when I switch back to A.txt, the cursor gets reset to the beginning of the file.

I can verify that it only happens when I'm using amVim. Disabling it or using other vim plugins doesn't reproduce the issue.

**Comment by nerdo** [comment]
I figured out how to reproduce it.

1. Open a file that doesn't fit within the screen and move the cursor so that the entire screen scrolls.
2. Enter insert mode by pressing i.
3. Switch to another tab in the workspace.
4. Switch back to the previous tab.

At step 4, you should notice that the cursor reverts back to normal mode and the cursor is automagically moved to the beginning of the file, scrolling the window with it.

**Comment by aioutecism** [comment]
Thanks! I'll check this one later.

**Comment by strothj** [comment]
I'm running into this issue every time I switch tabs with the "start in insert mode" option.

**Comment by xg-wang** [comment]
The fixed PR works fine for me.

**Comment by aioutecism** [comment]
Fixed in 1.23.1.
