### ISSUE TITLE
After join lines (J) cursor should move to space between joined lines

### ISSUE THREAD

**Issue by santialbo** [aioutecism/amVim-for-VSCode#179]
When you join two lines by pressing capital J the cursor should move to the space in between the two joined lines. Right now it stays where it is.

I might try to take a look myself this weekend. Just openening this issue for reference.

**Comment by aioutecism** [comment]
Thank you for point out this one.
PRs are very welcomed!

**Comment by aioutecism** [comment]
Fixed in 1.28.2.
