### ISSUE TITLE
When I use the mouse cursor, the cursor will always move forward one character at a time.

### ISSUE THREAD

**Issue by fenglinnet** [aioutecism/amVim-for-VSCode#182]
When I use the mouse cursor, the cursor will always move forward one character at a time.This often leads to copy&cut lost the last character.Maybe I'm not a depth of vim users, there are still heavy mouse operation.If this behavior can change or have a setting, that will be happy:)

**Comment by aioutecism** [comment]
Can't reproduce on the latest version.
Cloud you upload screenshots to the issue?

**Comment by aioutecism** [comment]
Closing since not reproducible.
