### ISSUE TITLE
VIM like navigation in sidebar

### ISSUE THREAD

**Issue by kkorus** [aioutecism/amVim-for-VSCode#188]
Is it able to have vim like navigation in sidebar? Like VSCodeVim (https://github.com/VSCodeVim/Vim) has?
`gg,G, h (to fold), j, k, l (to expand folder)`

**Comment by aioutecism** [comment]
Great feature.
Will find time to add it.

**Comment by aioutecism** [comment]
adf

**Comment by kkorus** [comment]
You would need to overwrite some keyboard bindings:

![image](https://user-images.githubusercontent.com/2054009/34219536-64d69ed0-e5a9-11e7-9f30-8f92a60d0fef.png)

**Comment by aioutecism** [comment]
Added in 1.24.0.
#193
