### ISSUE TITLE
Clicking exits Visual mode

### ISSUE THREAD

**Issue by lf94** [aioutecism/amVim-for-VSCode#19]
In both vim and gvim, when you click while in visual mode, the selection should expand to the character (or line if in visual line mode) of the click.

**Comment by aioutecism** [comment]
Extension doesn't know if a selection change is made by keyboard or mouse.
So this is very difficult to implement using the current VSCode's API.

**Comment by colbyrussell** [comment]
Which version of Vim are you using?  The behavior in comment 1 doesn't match what happens on my system.

**Comment by aioutecism** [comment]
I'm closing this one since it's not common vim behavior.
