### ISSUE TITLE
Colon in NORMAL mode to open Goto Line command window.

### ISSUE THREAD

**Issue by jasonlfunk** [aioutecism/amVim-for-VSCode#190]
I have set up the following keybinding:

```
{
    "key": "shift+;",
    "command": "workbench.action.gotoLine",
    "when": "editorTextFocus && amVim.mode == 'NORMAL'"
}
```

However, the Goto Line window opens no matter what mode I'm in. It's like VSCode is ignoring the amVim mode entirely. Is there something I'm missing here? Or is what I want to achieve not possible?

**Comment by aioutecism** [comment]
This is not possible by custom keybinding.

I've added the command here: #192.
Please update the extension and enjoy.

**Comment by jasonlfunk** [comment]
Thank you so much for doing this!
