### ISSUE TITLE
Editing or deleting or selecting inner html tags not working. 

### ISSUE THREAD

**Issue by mdcharaf** [aioutecism/amVim-for-VSCode#194]
```

- windows 10
- vscode 1.19.3
- amVim 0.10.13

```

Editing  ,deleting, and selecting inner html tags using "dit" "cit"  "vit" are not working.

**Comment by aioutecism** [comment]
Tag Text Object is not supported.
Please wait for updates.

**Comment by skube** [comment]
Any movement on this? 😬

**Comment by aioutecism** [comment]
@skube 
Not yet. Will find time to implement this soon.

**Comment by austenc** [comment]
Hello @aioutecism, I was looking into implementing this and wanted to write some tests first. Have a couple questions:
- Is there a code example that comes to mind for something similar which is already implemented? _reference material or a general idea of how we might do it would be helpful_
- Is there a way to test that something starts in a given mode and ends in another one? 
- Are there any tests for `c` yet? Perhaps a good start would be adding some of those. 
- As far as running the tests, what's your usual workflow for continually running a single suite or test(s) you're currently working on?

Thank you!

**Comment by aioutecism** [comment]
Hi @austenc ,

Thanks for your comment! To answer the questions.

> - Is there a code example that comes to mind for something similar which is already implemented? reference material or a general idea of how we might do it would be helpful

The Block TextObject works very much similar (https://github.com/aioutecism/amVim-for-VSCode/blob/master/src/TextObjects/Block.ts). The difficult part is we need to  more logic on finding the corresponding tag.

> - Is there a way to test that something starts in a given mode and ends in another one?

We don't have this kind of test functionality now.
However, current mode is available through `Dispatcher.currentMode`, so shouldn't be hard to do.

> - Are there any tests for `c` yet? Perhaps a good start would be adding some of those.

No tests for `c` yet. But we have tests for [`di{`](https://github.com/aioutecism/amVim-for-VSCode/blob/master/test/ModeNormal/d%20i%20%7B.test.ts) and [`da{`](https://github.com/aioutecism/amVim-for-VSCode/blob/master/test/ModeNormal/d%20a%20%7B.test.ts). Should be very similar.

> - As far as running the tests, what's your usual workflow for continually running a single suite or test(s) you're currently working on?

Changing `suite` to `suite.only` allows you to run only one test. I recommend using the test feature integrated into VSCode so the tests run in real environment.

**Comment by austenc** [comment]
I've added a PR for this feature https://github.com/aioutecism/amVim-for-VSCode/pull/247

**Comment by alisonatwork** [comment]
Closing this ticket now that #247 is in master. Hopefully we can push a release to the extension marketplace soon.
