### ISSUE TITLE
Number + command + movement not working

### ISSUE THREAD

**Issue by spicydonuts** [aioutecism/amVim-for-VSCode#198]
`2df<space>` on the following line while the cursor is on the first character simply moves the cursor right one character:
`hashFuncNames: ["sha256", "sha384"],`

It should delete characters up to the 2nd `<space>` character, leaving this text: `"sha384"],`

**Comment by aioutecism** [comment]
Only some of the commands support number before them.
Will add number support to `d` soon.

**Comment by aioutecism** [comment]
This is now supported in 1.27.0.
