### ISSUE TITLE
Numbers before commands

### ISSUE THREAD

**Issue by Raynes** [aioutecism/amVim-for-VSCode#20]
I can't, for example, do `2dd` to delete two lines. Looked through open tickets and didn't see one for this, apologies if its a dupe.

**Comment by lf94** [comment]
Yeah, he has a list on issue 1 that shows the compatibility.

Partial	N dd	delete N lines

So most of the time, he said that Partial means there's no N support. I'm hoping to contribute a bit to this. I'm done with slow Emacs (even though evil mode is pretty damn good) and gvim plugin hell. VS:C with GOOD Vim support is what I want to see, and I think amVim is on the right track compared to the others.

**Comment by aioutecism** [comment]
Yes, `Partial` means no N support most of the time.

**Comment by aioutecism** [comment]
`Ndd` is supported in 1.22.0.
Others are coming soon.
