### ISSUE TITLE
j doesn't go to next "virtual" line like down-arrow does

### ISSUE THREAD

**Issue by lf94** [aioutecism/amVim-for-VSCode#21]
1. Turn on text wrapping in user settings.
2. Press j on a line that's wrapped - it'll go to the next "real" line
3. Go back and press down-arrow. It'll go to the next "virtual" line, which is the same line but wrapped creating multiple lines within the line.

**Comment by aioutecism** [comment]
VSCode doesn't give an API to access visual line as far as I know.
I haven't find a work around yet.

**Comment by lf94** [comment]
Is there no way to simulate down-arrow?

**Comment by aioutecism** [comment]
Good idea!
There are built-in `cursorDown` and `cursorDownSelect` I can make use of.

BTW, I think it should be `gj` and `gk` that do the "screen movement".

**Comment by lf94** [comment]
Where did you find those functions? I'd like to help you with this project, but VSCode documentation is sort of sparse. I looked into TextDocument last night and a few other basic classes. I was considering switching back to Emacs but I would really like to make this work. Do you have an IRC channel we can talk in? Or email?

**Comment by aioutecism** [comment]
There is a `commands.getCommands()` to return all available commands.
The default keybinding file also contains these commands.

**Comment by aioutecism** [comment]
You can send me email but I'd rather you discuss here so everyone can see and search.

**Comment by lf94** [comment]
Alright, I'll keep our discussions here.

Is there a reason why you've created your own handlers and use .translate(), rather than use the movement commands already provided? You would avoid having to fight the editor. On my fork I'm modifying it to use the editor commands rather than the low-level .translate() you've created.

**Comment by aioutecism** [comment]
VSCode's built-in commands only provides "actions" which is impossible to reuse in Vim's system.
In specific, I need to split "motion" with "action" so that motions can do things other than moving cursor.
For example, passing a set of motions to `delete` action would delete anything those motions cover.

**Comment by colbyrussell** [comment]
This is what `gj` and `gk` are for.  This issue should be closed.

**Comment by aioutecism** [comment]
Since `gj` and `gk` are in the command list (#1), I'm closing this one.

**Comment by karlhorky** [comment]
The keybindings below seem to work for amVim normal mode for moving among displayed lines in word wrapping mode (similar behavior to `gj` and `gk`).

Ref: My pull request to VSCodeVim https://github.com/VSCodeVim/Vim/pull/3623

```js
  {
    "key": "up",
    "command": "cursorUp",
    "when": "editorTextFocus && amVim.mode == 'NORMAL' && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "down",
    "command": "cursorDown",
    "when": "editorTextFocus && amVim.mode == 'NORMAL' && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "k",
    "command": "cursorUp",
    "when": "editorTextFocus && amVim.mode == 'NORMAL' && !inDebugRepl &&!suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "j",
    "command": "cursorDown",
    "when": "editorTextFocus && amVim.mode == 'NORMAL' && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  }
```

**Comment by alisonatwork** [comment]
The work to support these motions using standard vim keys is being done in #116, and will be available in the next release.
