### ISSUE TITLE
ctrl+v visual mode selection

### ISSUE THREAD

**Issue by Toeplitz** [aioutecism/amVim-for-VSCode#211]
Trying to select text using ctrl+v visual mode does not appear to be working.

Is this a bug or is it not supported?

See attached example of this works in normal vim.
![capture](https://user-images.githubusercontent.com/304097/41523926-f70a0408-72db-11e8-91e1-986a2d86044f.PNG)

**Comment by aioutecism** [comment]
Visual Block mode is not supported yet.
Please subscribe to #62 to keep updated.

**Comment by toddljones** [comment]
+1 let's do this! as in, somebody else do this and submit the PR. thanks!
