### ISSUE TITLE
Search goes into the selection

### ISSUE THREAD

**Issue by sethstha** [aioutecism/amVim-for-VSCode#220]
While searching using the `ctrl + f` and hitting `return` or an `enter`, it selects the first occurrence. While hitting another `return` should navigate  to next occurrence.

Vscode: 1.24.1
OS: Mac OS High Sierra 
Plugin Version: 1.29.2

**Comment by aioutecism** [comment]
This is a intended behavior.

In Vim, after you confirm the search pattern with `enter`, the focus moves back to the editor. You then use `n` and `N` to navigate to 'next' and 'previous' occurrence.

**Comment by sethstha** [comment]
Isn't there any way to disable this behaviour? Since, it is overriding the default behaviour of vscode  even when I am in insert mode. This is not a problem with other plugins like `Vscode Vim` but those are heavy and bulky `amVim` is your choice when you only want to use vim style navigation and selection.

**Comment by aioutecism** [comment]
Might be good to add a setting for this behavior.
Will do this soon.

**Comment by aioutecism** [comment]
Added the config `amVim.mimicVimSearchBehavior` in 1.30.0.
Please set it to `false` to get your desired behavior.

**Comment by sethstha** [comment]
Superb! so fast.
