### ISSUE TITLE
⌘ + F only finds once

### ISSUE THREAD

**Issue by skube** [aioutecism/amVim-for-VSCode#222]
With the amVim extension enabled, I can only Find once. Hitting `enter` after will not find the next occurrence.

With amVim disabled, Find works as I expect and I can find the next occurrence simply by hitting `enter`.

**Comment by aioutecism** [comment]
Hi @skube,

I changed the default behavior when pressing `enter` in the search box so it's consistent with Vim. See #218.

If you prefer the VSCode's behavior, please try setting `amVim.mimicVimSearchBehavior` to `false`.

This configuration is added in 1.30.0.
