### ISSUE TITLE
AmVim causes cursor to stop responding

### ISSUE THREAD

**Issue by compostbrain** [aioutecism/amVim-for-VSCode#225]
Apparently at random I will be editing a file and the cursor will stop responding to keyboard input. At first I thought maybe it had to do with having too many tabs open but this does not seem to be the case.  

If I disable the plugin the behavior disappears. 

 My setting can be viewed [here](https://gist.github.com/compostbrain/6a8f72b73ac76edbe68cc0bd3507d601)

**Comment by aioutecism** [comment]
Hi @compostbrain,

Is this happening with every file types or just specific ones?

Besides, cloud you try to disable all other extensions except amVim and see if the behavior persist?

**Comment by canadaduane** [comment]
I've experienced this recently as well. All document editing froze, but strangely, I was able to still use cursor keys (NOT hjkl) to move the cursor.

**Comment by alisonatwork** [comment]
Have you seen this problem happen again in more recent versions of VS Code and amVim?
