### ISSUE TITLE
Features:EasyMotion and cs

### ISSUE THREAD

**Issue by zhaotongxue** [aioutecism/amVim-for-VSCode#232]
Easymotion is very useful in jump in line, now i jump in lines by using MetaGo,which only support find chars(equally with using <leader><leader>s in vim easymotion.) if jump into lines,it's not useful(which can be easily done by using <leader><leader>j or <leader><leader>k).I know "g",but the number is hard to remember,do you think so?so,what do you think about add this function into amVIM?(vscode-vim is to heavy,and slow to start up)
one command useful is "cs",eg:  public static void main[String args[]]{},to correct the [] to (), i can use cs[( to make it public static void main(String args[]){},it especially when type many brackets。What do you think about this command.
thanks.

**Comment by aioutecism** [comment]
Yes, they are useful features.

You can subscribe to #148 for EasyMotion implementation.
And I believe `cs[(` is supported by vim-surround. Please subscribe to #53 if you are interested.
