### ISSUE TITLE
Support "." (dot) for repeat last change

### ISSUE THREAD

**Issue by giggio** [aioutecism/amVim-for-VSCode#24]

**Comment by aioutecism** [comment]
As far as I know, `N .` means "repeat last change (with count replaced with N)".

**Comment by lf94** [comment]
. repeats last change, which is different from redo.

Lets say I type:

i

this is some text

ctrl+c

and then I press .

It will repeat my last command, which ends up re-typing "this is some text" at my current position.

**Comment by aioutecism** [comment]
`N .` is in the roadmap but has lower priority.

**Comment by giggio** [comment]
Repeat last change, used with a dot, is not yet working. I just tried it. I changed something with `cw` + some text, then `ESC`, then moved to a new location and then `.`, it did not repeat my change.
This is easily one of the most used features in Vim, it should not have low priority.

**Comment by aioutecism** [comment]
Sorry, I didn't know this one is used so much.
I'll add it soon.

**Comment by mpseidel** [comment]
@aioutecism thanks for pushing vim on vscode forward! the `.`-command was the first thing I found wasn't there, so +1 :)

**Comment by aholub** [comment]
Please please please add this. In normal vim, I use . every few minutes.

**Comment by aioutecism** [comment]
Added in 1.2.0.
Deletion made in insert mode won't be repeated due to lack of `backspace` and `delete` event now.
Repeat in visual and visual line modes are not implemented yet. It should be pretty easy to add though.

**Comment by espinoza** [comment]
(Sorry for comment an old issue, I did't find another place to comment this)

The dot command doesn't work exactly like Vim. If I do `5.`, it repeats the last action 5 times, but then I have to press `u` 5 times, or press `5u`. In Vim, I just have to press `u` to undo what I did pressing `5.`

Was this intentional?

Thanks.
