### ISSUE TITLE
Previous / Next word selection break

### ISSUE THREAD

**Issue by jleclanche** [aioutecism/amVim-for-VSCode#241]
Reproduce by writing the following in an empty file:
```
print(foo)
print(foo)
```

Then move the cursor somewhere on `print` and hit `*` or `#` a few times. Eventually, it breaks and stops moving to the next selection.

I can't tell exactly what is happening there. :/

**Comment by alisonatwork** [comment]
Does this still happen for you? I can't reproduce it.

**Comment by jleclanche** [comment]
Nope can't repro anymore.
