### ISSUE TITLE
Insiders Helper goes eats all CPU every time I open a SVG file

### ISSUE THREAD

**Issue by seawatts** [aioutecism/amVim-for-VSCode#244]
https://github.com/Microsoft/vscode/issues/20720

**Comment by alisonatwork** [comment]
Hi @seawatts I have tried to reproduce this with VS Code 1.45.1, amvim 1.31.0 and the `search.svg` provided on the linked issue and it does not seem to be happening. Please reopen this ticket with some steps to reproduce if it is still causing a problem for you.
