### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by alisonatwork** [aioutecism/amVim-for-VSCode#251]
Hi @aioutecism 

Just wondering if you are still maintaining this project? There are several outstanding pull requests that seem reasonable to me (#216 #217 #228 #236 #247 #250) and some low hanging fruit issues that I (or others) may be happy to work on (#212). For some of the PRs that are just missing a test or need conflict resolution, I would be happy to help out, as long as I know they'll get merged 😊 

I really find this plugin valuable - it is much better than the other vim plugins - so would love to see work on it continued and a new version released back to the extensions marketplace.

Thanks for all your work on this extension up until now, hope to hear soon 😁

**Comment by karlhorky** [comment]
It seems like @jackfranklin (author of #216) got contributor status last year:

https://twitter.com/aioutecism/status/1081054361197850624

But not sure if this has materialized into anything yet.

**Comment by jackfranklin** [comment]
Hey both,

I do indeed have permission to merge PRs. I was hopeful that I'd pick up this plugin + maintain it more frequently but I haven't because of time pressures but also I am a very happy user of this plugin :)

I'm happy to try to help out + merge PRs that make sense but I don't have permission to publish the library on the VSCode package site so we might need some of @aioutecism's help on that.

**Comment by karlhorky** [comment]
@aioutecism would you be open to also allowing either Alison or someone else with more time to take over more work as a maintainer?

**Comment by aioutecism** [comment]
Hey,

I may not able to put a lot of time into this plugin due to limited capacity. But I'm happy to review, merge and publish.

@jackfranklin Really appreciate that! Please feel free to merge PRs and I'll make sure to publish new versions when needed.

**Comment by alisonatwork** [comment]
Thanks for the responses @jackfranklin and @aioutecism! Good to hear there is still some life here and to see a couple of the PRs merged.

Looking at what is outstanding, I think we have:

1. Prettier (formerly #216 now #254) - this will have a lot of conflicts, not sure if it'd be better to try get the other ones merged before or after?
2. Goto end (#228) - the only thing missing here is a test; I can cherry-pick and reopen that with a test if the original contributor is not responsive
3. Goto definition (#250) - this one is more philosophical, to decide if the shortcut is being used correctly, maybe for @aioutecism to confirm?
4. HTML/XML tag object (#247) - probably just needs a rebase and sad path test; another one I can cherry-pick and reopen if the original contributor is not responsive
5. Upgrade dependencies (#217) - this seems like a good thing to do before publishing a new release, but the current PR might be out of date now?

It would be cool if we could get a new release in the Lunar New Year (next week). Jack, feel free to ping me on 2. or 4. if the original contributors don't have time.

**Comment by alisonatwork** [comment]
Update, I have cherry-picked the commit from #228, added tests and reopened as #255.

**Comment by alisonatwork** [comment]
Just a quick roundup here. Several of the above-mentioned PRs have now been merged, which is great.

1. Prettier #254 has been merged
2. Goto end, reopened as #255 has been merged
3. Goto definition, reopened as #258 is still waiting for review
4. HTML/XML tag object #247 has been reviewed and approved by @aioutecism but not yet merged
5. Update dependencies, reopened as #259 is still waiting for review

One new PR has been added - #260 to copy/paste from system clipboard.

@jackfranklin and @aioutecism do you have an update? 2 of (now) 6 open PRs have been merged, and 1 more has been approved although not yet merged. If you don't have time to review the outstanding 3 PRs, perhaps it would at least be viable to merge the approved PR and push a new release to the extensions marketplace?

**Comment by karlhorky** [comment]
@aioutecism @jackfranklin it seems like you do not have enough time to maintain this project - would you be open to adding @alisonatwork as a maintainer?

She has been active here and I believe she will take good care of the project.

**Comment by jackfranklin** [comment]
Yes, that would be great. I'm sorry that I've not been able to help much
here.

**Comment by jackfranklin** [comment]
I don't have permissions to do it - but @aioutecism can! Let's:

* add @alisonatwork as a contributor / maintainer
* Allow Alison to publish the library on the Code site?

**Comment by alisonatwork** [comment]
Thanks for volunteering me, Karl, though i'm not sure i'm really an expert in TypeScript or VS Code extensions! That said, i am happy to keep learning and contribute more actively. I use this extension every day at work and would love to see some of these quality-of-life improvements get through.

**Comment by karlhorky** [comment]
@alisonatwork Although the time I can devote seems like less than you, I would be happy to assist you here in whatever way I can. I've worked with TypeScript / Flow for the last 3 years, and have held workshops teaching it.

I'm a newbie when it comes to VS Code extensions, but I'm sure that we can figure it out, either together or with help from any other community members.

**Comment by aioutecism** [comment]
Sorry for the slow response. I'm very happy to have @alisonatwork helping maintain this project. Just sent the invitation :)

Please ping me whenever you need to publish a new version to the VSCode store. I'll try my best to do it as soon as possible.

(Again, I apologize for being unresponsive recently. As I switched my career to a different role, I don't have enough time to put into coding and developing as before…)

**Comment by alisonatwork** [comment]
Thanks for the add @aioutecism! I will take a look at merging the PRs that seem safe and pass the tests on Node 8, then I suggest we release that as extension version 1.31.0. After that it might be worth looking at bumping Node to the current LTS (12) and looking at the trickier PRs.

**Comment by alisonatwork** [comment]
@aioutecism would you be able to package up the current master and release it to the marketplace as `1.31.0`? The changelog will include:

- go to percent in file
- `zt` cursor to top
- `{N} ~` multiple switch case
- `g ?` ROT13
- text object for html/xml (`cit`, `dit` etc)
- misc doc and dependency upgrades

I think for safety we can leave the `gd` motion change and system clipboard feature to next version. These changes should already make a lot of users pretty happy!

**Comment by aioutecism** [comment]
@alisonatwork 
Thanks! Just published a new version to Marketplace :)

**Comment by alisonatwork** [comment]
That's fantastic, thanks! I will close this ticket now since the original question has been resolved, and will open a new one once we are ready for the release 👍
