### ISSUE TITLE
Extension issue: Illegal value for `line`

### ISSUE THREAD

**Issue by rokoroku** [aioutecism/amVim-for-VSCode#252]
- Issue Type: `Bug`
- Extension Name: `amvim`
- Extension Version: `1.30.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.40.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 191,
		"activateCallTime": 8,
		"activateResolvedTime": 17,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "auiworks.amvim",
				"_lower": "auiworks.amvim"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Illegal value for `line`"
		}
	]
}
```

**Comment by alisonatwork** [comment]
Do you have any more context around when or why this happened, if not, I will close this issue.
