### ISSUE TITLE
Conflict with VS Code autoClosingBrackets

### ISSUE THREAD

**Issue by amkgo** [aioutecism/amVim-for-VSCode#27]
After installing this plugin, the VS Code auto closing bracket function is broken.

1. When I type `function show(` the `)` shows automatically as `function show()`, but when I type another `)`, it becomes `function show())` and the cursor is stayed in the middle of two `))`. Only if I input something into the bracket like `function show(msg)` then the cursor moves to the end without any problem.

2. After I type `function show(msg) {` the `}` doesn't show out automatically.

Andrew

**Comment by aioutecism** [comment]
Insert mode is missing some functionality due to VSCode not providing custom keybinding context support. (Requested here: https://github.com/Microsoft/vscode/issues/1432)
I'll do something with `()`, `{}` and `[]` before VSCode supports it.

**Comment by aioutecism** [comment]
This should be solved in 1.0.0.
However, 1.0.0 depends on VSCode >= 0.10.12.
You can download the VSCode insiders version [here](https://code.visualstudio.com/insiders) and install amVim to try it.
