### ISSUE TITLE
Support "inside" command

### ISSUE THREAD

**Issue by JakeStevenson** [aioutecism/amVim-for-VSCode#28]
The "i" modifier to many commands allows it to affect all text "inside" characters.  For example, "ci)" would call "change inside parenthesis", finding the first ( to the left of the current cursor and deleting the text to the first ) to the right of the current cursor, then switching to insert mode.  This works with many commands like d for delete, y for yank, v for visual block, etc.

It's a huge productivity boost and an key benefit of vim keybindings.

**Comment by aioutecism** [comment]
This will be supported by text objects: #13

**Comment by aioutecism** [comment]
Parts of text objects are supported in 1.3.1.
See #1 "Text objects (only in Visual mode or after an operator)" for detail.
