### ISSUE TITLE
code duplication in Dispatcher's mode registration

### ISSUE THREAD

**Issue by ghost** [aioutecism/amVim-for-VSCode#30]
`modes` gets defined, and then we iterate over a second array literal containing them.

**Comment by colbyrussell** [comment]
````
The following changes since commit dd9013ca546b86fcc78d9a2cb4fb6c77d97fea07:

  Update version to 0.0.15. (2016-01-18 22:00:51 +0900)

are available in the git repository at:

  git@gitlab.com:crussell/amVim.git modereg

for you to fetch changes up to b21fd8511fb7a0d73c7f056159ed9bbcacbae771:

  Refactor mode registration (2016-02-02 22:21:11 -0600)

----------------------------------------------------------------
Colby Russell (1):
      Refactor mode registration

 src/Dispatcher.ts | 11 +++--------
 1 file changed, 3 insertions(+), 8 deletions(-)
colby@ruta-corsica:~/projects/amvim/src$ 
````

**Comment by aioutecism** [comment]
Thank you so much for your contribution.
Could you upload your project to GitHub and create a pull request from your branch to this repo's master branch?
That is much easier to discuss about the code and merge.
(And your name will be in the contributors page once the code is merged.)

**Comment by colbyrussell** [comment]
I don't use GitHub to host anything.

**Comment by aioutecism** [comment]
I understand.
Is it ok that I merge your modification into this repo?

**Comment by colbyrussell** [comment]
Yes, of course.

(Even if you asked and I said, "no", the license would still give you permission to do it.)

**Comment by colbyrussell** [comment]
PS: if you want to leave comments on a commit for a project hosted on GitLab, you can sign in using your GitHub account (or Twitter, or Bitbucket, or Google...)
