### ISSUE TITLE
Caps lock broken in Insert Mode

### ISSUE THREAD

**Issue by ghost** [aioutecism/amVim-for-VSCode#34]
# STR
1. Open a new file.
2. Hit `I` to enter insert mode.
3. Attempt to type "FOO BAR BAZ"

# Results

It comes out as "fOO bAR bAZ"

**Comment by aioutecism** [comment]
This should be solved in 1.0.0.
However, 1.0.0 depends on VSCode >= 0.10.12.
You can download the VSCode insiders version [here](https://code.visualstudio.com/insiders) and install amVim to try it.
