### ISSUE TITLE
race conditions with motions and revealing `InCenterIfOutsideViewport`

### ISSUE THREAD

**Issue by ghost** [aioutecism/amVim-for-VSCode#35]
Sometimes when the viewport gets scrolled when using `j` or `k`, it doesn't scroll one line at a time, but instead it's more like it's scrolling a half-page at a time with the cursor jumping to the middle every time, i.e., similar to what would happen in Vim if you held down `j` and then pressed `zz` every time you reached the bottom of the screen.

This looks like it might be a race condition involving `MoveCursor.byMotions`, `ActionReveal.primaryCursor`, and the vscode framework.  I.e., the async calls start falling behind, so the cursor is off the screen by the time the call to `revealRange` is made.

To see this, try using `j` to scroll through a long file, like extHost.api.impl.ts from the vscode source.  It may be hard to catch at first, so it may help by trying this while your computer is running under a load.  (I originally was going to suggest restarting VSCode just before trying to reproduce this, but it looks like that actually makes it harder to observe.  Instead just try using the button in the Explore sidebar to close all working files, closing all open editors, and then opening, e.g., exHost.api.impl.ts.)  After a while, I can reliably trigger this when pressing `j` a single time to move down to a partially off-screen line, even with no significant background CPU load.

**Comment by aioutecism** [comment]
Should be solved in VSCode 0.10.8 and amVim 0.1.0.
