### ISSUE TITLE
yank and paste do not behave like in sublime

### ISSUE THREAD

**Issue by trivoldus28** [aioutecism/amVim-for-VSCode#36]
I'm transitioning from sublime, and the difference of yank and paste between this plugin and sublime is really bugging me. I can give an example if the author has not used or does not have access to sublime text; the main difference is that when pasting, the new text is inserted after the newline character instead of before, giving odd behavior.

Selecting these with v...
![image](https://cloud.githubusercontent.com/assets/2350008/12869785/5e3c3ac0-ccf7-11e5-9df9-8f1ba2f6ca22.png)

Yank, and paste from this position...
![image](https://cloud.githubusercontent.com/assets/2350008/12869790/70e0d226-ccf7-11e5-9ebf-1ca3808f6c6d.png)

And you get this...
![image](https://cloud.githubusercontent.com/assets/2350008/12869796/8c9f0dac-ccf7-11e5-881a-af4b8b10b976.png)

**Comment by Sean1708** [comment]
@trivoldus28 How do you expect it to work? As far as I can tell this is how standard Vim works, `p` pastes after the current character while `P` pastes before the current character.

**Comment by aioutecism** [comment]
Fixed in 1.17.4. See #152 for detail.
