### ISSUE TITLE
I cant write ;

### ISSUE THREAD

**Issue by imacnu** [aioutecism/amVim-for-VSCode#37]
In spanish keyboard not is posible write ; instead visual code whir this extension write <

**Comment by magbeat** [comment]
The same happens with a german keyboard layout.

**Comment by aioutecism** [comment]
- [ ] Need a pre-mapping class to deal with all non-us keyboard layout.

**Comment by imacnu** [comment]
how do it?

**Comment by aioutecism** [comment]
I haven't looked into this. I may need to check what VSCode is doing with different keyboard layout first.

**Comment by adamdicarlo** [comment]
*possibly* related: I use the Colemak keyboard layout and am finding the *first* time I try to insert a character after switching to insert mode, its QWERTY equivalent comes out. Subsequent inserts while still in insert mode produce the correct character.

**Comment by adamdicarlo** [comment]
Whoops, actually if I keep inserting the character, it alternates between inserting the QWERTY equivalent and the Colemak one. Pretty interesting.

For instance, trying to insert multiple semicolons inserts:

> p;p;p;p;p...

(Colemak's semicolon is where "p" is on a QWERTY keyboard)

**Comment by aioutecism** [comment]
@imacnu @magbeat @adamdicarlo 

I added keyboard layout support here: #45.

It has only the `US QWERTY` layout now. Could you help creating layout you need?
All it needs is a file like this:
https://github.com/aioutecism/amVim-for-VSCode/blob/feature/keyboard-layout-support/src/Layouts/US_QWERTY.ts
You may like to check #45 for guidance of creating layout file.

**Comment by adamdicarlo** [comment]
@aioutecism awesome, thanks! I'd love to do that! Will PR it against your branch (assuming your branch is not merged yet when I get it going).

**Comment by aioutecism** [comment]
All layout related problems should be solved in 1.0.0.
However, 1.0.0 depends on VSCode >= 0.10.12.
You can download the VSCode insiders version [here](https://code.visualstudio.com/insiders) and install amVim to try it.
