### ISSUE TITLE
Not work $ in "Dvorak Programmer" keyboard layout

### ISSUE THREAD

**Issue by T0toro** [aioutecism/amVim-for-VSCode#44]
Not work $ in "Dvorak Programmer" keyboard layout in mac os x 10.10

**Comment by aioutecism** [comment]
Hi @T0toro 

I added keyboard layout support here: #45.

It has only the `US QWERTY` layout now. Could you help creating layout you need?
All it needs is a file like this:
https://github.com/aioutecism/amVim-for-VSCode/blob/feature/keyboard-layout-support/src/Layouts/US_QWERTY.ts
You may like to check #45 for guidance of creating layout file.

**Comment by aioutecism** [comment]
![kb_programmer_dvorak](https://cloud.githubusercontent.com/assets/2175401/13693448/9ea773c0-e78e-11e5-92e1-8f58172a8908.png)

**Comment by aioutecism** [comment]
I tried using [this](http://www.kaufmann.no/roland/dvorak/macosx.html) layout.
VSCode seems not supporting all the mappings.
Only tested on OSX.

**Comment by T0toro** [comment]
Yes, I use this layout too. 

I have also tested simply dovorak, in him just the same е mistakes on ubuntu, arch and mac os x.

**Comment by aioutecism** [comment]
All layout related problems should be solved in 1.0.0.
However, 1.0.0 depends on VSCode >= 0.10.12.
You can download the VSCode insiders version [here](https://code.visualstudio.com/insiders) and install amVim to try it.

**Comment by T0toro** [comment]
Good work, Thanks!!!!
