### ISSUE TITLE
emmet abbreviations don't expand with Tab

### ISSUE THREAD

**Issue by rob3c** [aioutecism/amVim-for-VSCode#47]
Hi, thanks for the awesome extension! It's great to have vim bindings working in an organic way with VSCode.

Unfortunately, it looks like something with `Tab` key handling breaks emmet abbreviation expansion. For example, typing the [vscode docs sample](https://code.visualstudio.com/docs/editor/editingevolved#_snippets-and-emmet-abbreviations) `ul.generic-list>lorem10.item*4` in insert mode and then hitting `Tab` just inserts a tab character instead of expanding the emmet expression.

**Comment by aioutecism** [comment]
AFAIK, this is impossible with the current extension APIs of VSCode.
All this kind of inconvenience will be solved after https://github.com/Microsoft/vscode/issues/1432 is addressed.

**Comment by rob3c** [comment]
Sorry to hear that. Hopefully, they'll address it sometime soon. Regardless, the benefits of the amVim extension still outweight that slight inconvenience for me and many others, I'm sure, so please keep up the great work! :)

**Comment by aioutecism** [comment]
This should be solved in 1.0.0.
However, 1.0.0 depends on VSCode >= 0.10.12.
You can download the VSCode insiders version [here](https://code.visualstudio.com/insiders) and install amVim to try it.

**Comment by rob3c** [comment]
Thanks, I look forward to trying it when I get a chance!
