### ISSUE TITLE
append after the cursor (aka 'a' key) does not work

### ISSUE THREAD

**Issue by hellmean** [aioutecism/amVim-for-VSCode#5]
if the cursor is at the end of the line the 'a' key does not append, but rather acts as 'i' key

Thanks a lot for this extension!! The other two are impossible. Owe you a beer!

**Comment by aioutecism** [comment]
Thx!
Fixed 7e771098427736a7fb67b42a06564fc087c299da

**Comment by hellmean** [comment]
aaahh) I just fixed it myself in the branch I cloned)

**Comment by aioutecism** [comment]
:laughing:
