### ISSUE TITLE
Use `getWordRangeAtPosition` to do word motion

### ISSUE THREAD

**Issue by aioutecism** [aioutecism/amVim-for-VSCode#52]
Respect language settings about word separators.

**Comment by colbyrussell** [comment]
Some problems with `getWordRangeAtPosition`:

- it tries to return a half-open range (start is inclusive, end is not), but it's more like a quasi-half-open range
- most of the time when the cursor is positioned inside non-words, it returns undefined, so with the current implementation, we will have to have our own scanner, anyway :/

The one exception to the latter point is that it *won't* return undefined if called from a position at the end of one of those half-open ranges.  For example, for the string `foo bar  baz   fum`:

- inside "foo" it returns character offsets [0, 3)
- inside "foo" it returns [4, 7)
- inside "foo" it returns [9, 12)
- inside "foo" it returns [15, 18)

But:

- for the space before "fum" it returns undefined
- for the space before "baz" it returns undefined
- for the space before "bar" it returns [0, 3)

I think this needs to be smoothed out upstream before we can really start using it.  Even if someone says, "the word's range end should point to an offset just past the end of the word", then I would say, "great, that's called a half-open interval, but the space after 'foo' and 'bar' and 'baz' should still be consistent with the subsequent spaces, and right now it isn't, which means sometimes it's treating the range as a half-open interval, and other times it's treating it as a closed interval".

**Comment by aioutecism** [comment]
Thanks for the investigation.
Maybe we can just get separators from configuration now.
https://github.com/alexandrudima/vscode-vim/blob/bf2af705a7bfb0fe6b3247a9b6b82624e0c6df67/src/extension.ts#L54-L57

**Comment by aioutecism** [comment]
Word motions refactored.
