### ISSUE TITLE
Navigating between split panes

### ISSUE THREAD

**Issue by kuon** [aioutecism/amVim-for-VSCode#64]
There is one important feature I am missing, is the ability to navigate between split panes with the keyboard, with vim keys like: `C-w l` to go 1 page right

**Comment by kylefinley** [comment]
@kuon 

I ran into this as well. I added the flowing to my `keybindins.json`. It's works relativelty well.
```json
  { "key": "ctrl+w h",             "command": "workbench.action.focusLeftEditor" },
  { "key": "ctrl+w l",             "command": "workbench.action.focusRightEditor" },
```

**Comment by aioutecism** [comment]
Thanks @kylefinley !

@kuon 
Window management is VSCode's built-in feature, thus you can configure it the way you like.
Here's my `keybindings.json`:

```json
[
	{ "key": "alt+cmd+s", "command": "workbench.action.files.saveAll" },

	{ "key": "cmd+k h", "command": "workbench.action.moveActiveEditorLeft" },
	{ "key": "cmd+k l", "command": "workbench.action.moveActiveEditorRight" },

	{ "key": "alt+h", "command": "workbench.action.focusLeftEditor" },
	{ "key": "alt+l", "command": "workbench.action.focusRightEditor" },

	{ "key": "alt+j", "command": "workbench.files.action.openNextWorkingFile" },
	{ "key": "alt+k", "command": "workbench.files.action.openPreviousWorkingFile" },

	{ "key": "ctrl+f12", "command": "editor.action.openDeclarationToTheSide", "when": "editorTextFocus" }
]
```

**Comment by kuon** [comment]
Ok, thanks for the tip, but I think a vim mode should provide this, or at least document it with a vim-like `keybindings.json` in the README.

**Comment by aioutecism** [comment]
Some other multi-window commands are in the road map #1, but with low priority.
Since `CTRL-W` is conflict with "Close current window", I'll add these commands with default off. You need to activate by set `amVim.bindCtrlW` to `true`.
