### ISSUE TITLE
`w` should move cross lines

### ISSUE THREAD

**Issue by aioutecism** [aioutecism/amVim-for-VSCode#65]

**Comment by ThatLousyGuy** [comment]
I'm trying to work on this right now along with {N} w, {N} e, etc.

What is MotionWordPosition.NEXT_BOUNDARY used for in Vim? I don't remember seeing it before.

**Comment by aioutecism** [comment]
@ThatLousyGuy 
NEXT_BOUNDARY is for use with "cw" where it should delete to the next boundary instead of word start. 
BTW, I'm going to refactor word related motions very soon. Cloud you wait until I finish refactoring?

**Comment by ThatLousyGuy** [comment]
Thanks! And sure, let me know when you're done

**Comment by aioutecism** [comment]
I refactored word motions.
They move across lines now.
