### ISSUE TITLE
Repeat command (dot .) is not working correctly

### ISSUE THREAD

**Issue by ppasieka** [aioutecism/amVim-for-VSCode#69]
I found some bug in extension

Scenario:
1. Go into INSERT mode
2. type something for example: TEST123
3. delete some characters. On screen you should see for example TEST
4. Exit insert mode
5. Use repeat command

You should expecte to see: TESTTEST. But output is  TESTTEST123

So .(dot) remember all typed characters.

**Comment by aioutecism** [comment]
Deletion and autocomplete are not recorded now. 
As memoed [here](https://github.com/aioutecism/amVim-for-VSCode/blob/9219f440c7c3cc1e740889ba545c6c9d452d5e05/src/Modes/Insert.ts#L101). 
I'm trying to find a workaround or asking VSCode team for new apis.

**Comment by aioutecism** [comment]
Fixed in 1.20.0.
Pull request here: #160.
