### ISSUE TITLE
Command 'dd' (delete line) doesn't work on the last line in the file

### ISSUE THREAD

**Issue by isvforall** [aioutecism/amVim-for-VSCode#71]
When I press `dd` on the last line in the file then nothing happens.

**Comment by DanEEStar** [comment]
I tried to debug it.
There is a strange behaviour in the VSCode API which seems to relate with this ticket.
I filed a ticket on the VSCode github:
https://github.com/Microsoft/vscode/issues/5704

**Comment by aioutecism** [comment]
Yes, the API is buggy. I'm going to fix it today.
Before then, I'll use custom implemented method to avoid the wrong behavior.

**Comment by isvforall** [comment]
It's working now, but still doesn't work for empty line

**Comment by aioutecism** [comment]
Hmmm, seems like position validating related motions need some refactoring.

**Comment by aioutecism** [comment]
This is fixed in 1.11.6.
