### ISSUE TITLE
repeat partial when typing '.'

### ISSUE THREAD

**Issue by Bruce313** [aioutecism/amVim-for-VSCode#76]
Hi, Thanks for The Great Work!

When I typing 'a' and I got 'hint-list' like 'abc, adefad, aefe', then I typing the 'Enter‘
So this will INPUT 'abc'
Then typing '.', VIM should Enter 'abc', not 'a'.

**Comment by aioutecism** [comment]
Duplicate of https://github.com/aioutecism/amVim-for-VSCode/issues/69#issuecomment-213701749
Deletion and autocomplete are not recorded now.
