### ISSUE TITLE
esc doesn't go to normal mode

### ISSUE THREAD

**Issue by DavidStrada** [aioutecism/amVim-for-VSCode#8]
Hey,

I'm OS X and when i press esc nothing happens, do i need to map ? trial an error i found that `control + p` goes into normal mode tho.

**Comment by aioutecism** [comment]
Hi,

The default mode is Normal. You may enter Insert mode by pressing `i`. And exit to Normal mode by pressing `Esc` in other modes.
Where did you get stuck? It would be helpful if you can write down how to reproduce the problem by step.

`Ctrl+p` is not bind anywhere in this extension. Cloud it be something wrong in your configuration?

**Comment by Liquidmantis** [comment]
The behavior I experience is that Esc has to be pressed twice usually because of the persistent "No suggestions" Intellisense issue.  Likewise Enter has to be pressed twice.

**Comment by DavidStrada** [comment]
Pretty much what i did download a new version of VSCode and start installing plugins ( the ones that i need the most ) e.g. VIM discovered yours installed it and ESC key does not work, I haven’t touch any default config files of any kind. I was able to get `Normal` mode by pressing Ctrl + p.

Thanks,
David

**Comment by aioutecism** [comment]
@DavidStrada 

This is weird. Did you restart VSCode after installing the extension?

**Comment by aioutecism** [comment]
@Liquidmantis 

Yes, IntelliSense is buggy right now. 
I'm asking for feature support from VSCode [here](https://github.com/Microsoft/vscode/issues/1432)

**Comment by aioutecism** [comment]
Hi, @DavidStrada 

How's it going?
Are the bug still there?

**Comment by DavidStrada** [comment]
Hey, uninstalled and reinstall everything now working!
Feel free to. Close it tho.

Thanks

**Comment by aioutecism** [comment]
Great!
