### ISSUE TITLE
Delete word(dw) doesn't work correctly

### ISSUE THREAD

**Issue by isvforall** [aioutecism/amVim-for-VSCode#90]
E.g. I have this text:

>one two three four
five six
seven
eight

if I move cursor on the `f`letter of `four` word and press delete word(`dw`) it will delete an entire line with the following line too, i.e. result will be as follows

>seven
eight

**Comment by latipovsharif** [comment]
I've got the same issue, In addition i want to say that if word that I'm going to delete ends with new line than dw deletes next line entirely.

**Comment by aioutecism** [comment]
Fixed in 1.11.1.
