### ISSUE TITLE
Support repeated commands

### ISSUE THREAD

**Issue by ahakki** [aioutecism/amVim-for-VSCode#91]
If I want to delete the next 3 words I can use '3dw' in Vim. In amVim this just causes the cursor to go to the beginning of the next word (as if I had just pressed 'w').
Is this related to issue [84](https://github.com/aioutecism/amVim-for-VSCode/issues/84)?

**Comment by aioutecism** [comment]
Number before command are only supported by a few commands.
You may like to subscribe to #20 where I'll comment with updates.

#84 is not related.
