### ISSUE TITLE
Ctrl+[

### ISSUE THREAD

**Issue by guiwp** [aioutecism/amVim-for-VSCode#92]
Not working right with my keyboard layout:

    Layout Display Name    REG_EXPAND_SZ    @%SystemRoot%\system32\input.dll,-5003
    Layout File    REG_SZ    KBDBR.DLL
    Layout Text    REG_SZ    Portuguese (Brazilian ABNT)

What you suggest?

**Comment by aioutecism** [comment]
`Ctrl-[` is conflict with "outdent" and is not supported now.
I'll add the support with an additional setting like `amVim.bindCtrlC`.
Please use `Esc` or `Ctrl-C` (need to set `amVim.bindCtrlC: true` in setting) now.

**Comment by shamrin** [comment]
Just for your information: on OS X `Ctrl-[` doesn't conflict. Because `Cmd-[` outdents.

It's very hard to relearn and use `Ctrl-C` instead of `Ctrl-[` to escape. I don't remember why I've started using `Ctrl-[` in Vim. Good to know that I'm not alone doing it.

**Comment by shamrin** [comment]
I've implemented `Ctrl-[`: PR #102. It could be disabled by [`bindCtrlCommands` setting](https://github.com/aioutecism/amVim-for-VSCode#amvimbindctrlcommands).
