### ISSUE TITLE
Holding down movement key doesn't repeat movement

### ISSUE THREAD

**Issue by vlutton** [aioutecism/amVim-for-VSCode#93]
Holding down the movement keys `h,j,k,l,w` doesn't repeat the movement, forcing you to tap it every time.  There might be a setting to change this, but I couldn't find anything in the docs.  
I am using:
VSCode 1.1.0
AmVim 1.6.0
OS X El Capitan 10.11.4

Excellent extension overall!

**Comment by mentalbrew** [comment]
This is actually an El Capitan issue. You find the fix here: http://www.idownloadblog.com/2015/01/14/how-to-enable-key-repeats-on-your-mac/

**Comment by vlutton** [comment]
That fixed it!  Thank you very much for your quick response!  I will go ahead and close this out since the issue had nothing to do with amVim.  Thanks again for your help!

**Comment by slumtrimpet** [comment]
Not sure how I've been on this OS for years and never hit this one... but oh well, that does indeed fix this and I'm using vim nav keys like a champ now.  Thanks!

**Comment by swilliamset** [comment]
To disable macs default just for VS Code try https://stackoverflow.com/a/44010683

**Comment by texasbruce** [comment]
@swilliamset 's link works perfectly

**Comment by macgyver** [comment]
I'm glad for this thread! I fixed it on a per-app basis in VSCode via `defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false` but just curious - why did I not have to  do something similar for other applications like Atom?

**Comment by d48** [comment]
> This is actually an El Capitan issue. You find the fix here: http://www.idownloadblog.com/2015/01/14/how-to-enable-key-repeats-on-your-mac/

i've tested this and it works for OSX Mojave 10.14.4 as well
