### ISSUE TITLE
v1.6 locks the keyboard very often

### ISSUE THREAD

**Issue by localvar** [aioutecism/amVim-for-VSCode#95]
I didn't find out how to reproduce the issue, but after some normal mode editing, the keyboard is locked and cannot input anything, I had to restart VSCode to make it work again. this happens frequently, makes the plug-in unusable.

My OS is Windows 10
VSCode version is 1.1

**Comment by localvar** [comment]
seems the issue was caused by VSCode bug, everything is fine after upgrade VSCode to v1.1.1.
I will do more verification and close the issue if cannot reproduce it.

**Comment by localvar** [comment]
till encounter this issue, but frequency is much lower now.

**Comment by mpseidel** [comment]
@localvar this might be the same issue I am having #77 ?

**Comment by localvar** [comment]
@mpseidel 
yes, seems the dot command is root cause
