### ISSUE TITLE
'u' undo too much

### ISSUE THREAD

**Issue by localvar** [aioutecism/amVim-for-VSCode#98]
for example:
`dd` to delete one line then `dd` again to delete another line.
`u` will undo both.

**Comment by mpseidel** [comment]
Happening to me too

**Comment by aioutecism** [comment]
This is related to how VSCode is handling undo.
It's difficult to solve it until VSCode provides an API for history management.

**Comment by endel** [comment]
It seems to be fixed now.

**Comment by aioutecism** [comment]
This is fixed in the newest VSCode.
